import { createReadStream } from 'node:fs'
import { readdir, stat } from 'node:fs/promises'
import { createInterface } from 'node:readline'
import { homedir } from 'node:os'
import { join } from 'node:path'
import type { CliHistorySession, SearchSessionResult } from '../../src/types/workerDesk'

const QUALITY_SCAN_MAX_BYTES = 64 * 1024

function isAsciiAlphanumeric(c: string): boolean {
  const code = c.charCodeAt(0)
  return (
    (code >= 48 && code <= 57) || // 0-9
    (code >= 65 && code <= 90) || // A-Z
    (code >= 97 && code <= 122) // a-z
  )
}

/**
 * Encode a filesystem path to Claude's project directory name.
 * All non-alphanumeric characters (except hyphens) become hyphens.
 * Matches desktop-cc-gui's encode_project_path behavior.
 */
export function encodeProjectPath(projectPath: string): string {
  return projectPath
    .split('')
    .map((c) => (isAsciiAlphanumeric(c) || c === '-' ? c : '-'))
    .join('')
}

function normalizePath(value: string): string {
  return value.replace(/\\/g, '/').replace(/\/+$/, '').toLocaleLowerCase()
}

/** Get ~/.claude/projects/ directory */
function claudeProjectsDir(): string {
  return join(homedir(), '.claude', 'projects')
}

/** Truncate a string to maxChars, adding ellipsis if truncated */
function truncate(s: string, maxChars: number): string {
  if (s.length <= maxChars) return s
  return s.slice(0, maxChars) + '…'
}

/** Check if a user message should be filtered (meta/warmup/command) */
function isFilteredMessage(text: string): boolean {
  return (
    text.startsWith('<command-name>') ||
    text.startsWith('<command-message>') ||
    text.startsWith('<local-command-stdout>') ||
    text.includes('Caveat: The messages below were generated by the user while running local commands')
  )
}

/** Extract text from message content (string or block array) */
function extractTextFromContent(content: unknown): string {
  if (typeof content === 'string') {
    return content.trim()
  }
  if (Array.isArray(content)) {
    const parts: string[] = []
    for (const block of content) {
      if (!block || typeof block !== 'object') continue
      const blockType = (block as Record<string, unknown>).type
      if (blockType === 'text') {
        const text = (block as Record<string, unknown>).text
        if (typeof text === 'string') {
          const trimmed = text.trim()
          if (trimmed) parts.push(trimmed)
        }
      }
    }
    return parts.join('\n\n')
  }
  return ''
}

type ScannedSession = {
  sessionId: string
  firstMessage: string
  firstTimestamp: number | undefined
  lastTimestamp: number | undefined
  cwd: string
  fileSizeBytes: number
  userMessageCount: number
  assistantTextChars: number
  apiErrorCount: number
  containsGaTask: boolean
  qualityScanComplete: boolean
}

/**
 * Scan a single jsonl just enough to render a list card.
 *
 * Performance: project switching reads every jsonl in `~/.claude/projects/<encoded>/`,
 * and a typical CC session jsonl is several MB. Reading the whole file per card
 * stacks up to seconds for a project with dozens of sessions and is the main
 * source of UI jank when the user picks a project.
 *
 * What we actually need for the list:
 *   - firstMessage  → first non-meta user message text (almost always in the
 *                     opening lines of the file)
 *   - firstTimestamp → from the first entry that carries a timestamp
 *   - cwd            → from the first entry that carries cwd
 *   - lastTimestamp  → file mtime (CC fsyncs after the last write, so mtime is
 *                     equivalent to the last entry's timestamp without reading)
 *
 * We therefore stat() to get size + mtime, then stream at most the first 64KB.
 * If the stream ends before that cap, quality signals can be used for conservative
 * low-signal classification. If the cap is hit, the list still gets a title and
 * mtime, but the renderer must not treat partial quality signals as proof that
 * the whole session is low value.
 */
async function scanCliSessionFile(filePath: string): Promise<ScannedSession | null> {
  let fileSizeBytes: number
  let lastTimestampMs: number | undefined
  try {
    const s = await stat(filePath)
    fileSizeBytes = s.size
    const mtime = s.mtimeMs
    if (Number.isFinite(mtime) && mtime > 0) lastTimestampMs = mtime
  } catch {
    return null
  }

  if (!fileSizeBytes || fileSizeBytes === 0) return null

  let firstMessage: string | undefined
  let firstTimestamp: number | undefined
  let cwd = ''
  let sawAnyMessage = false
  let bytesRead = 0
  let userMessageCount = 0
  let assistantTextChars = 0
  let apiErrorCount = 0
  let containsGaTask = false
  let qualityScanComplete = true

  const fileStream = createReadStream(filePath, { encoding: 'utf-8' })
  const rl = createInterface({ input: fileStream, crlfDelay: Infinity })

  try {
    for await (const rawLine of rl) {
      bytesRead += Buffer.byteLength(rawLine, 'utf-8') + 1
      const line = rawLine.trim()
      if (!line) continue

      let entry: Record<string, unknown>
      try {
        entry = JSON.parse(line) as Record<string, unknown>
      } catch {
        // Malformed line (e.g. incomplete write at EOF) — skip
        continue
      }

      if (!cwd) {
        const entryCwd = entry.cwd
        if (typeof entryCwd === 'string' && entryCwd.trim()) {
          cwd = entryCwd.trim()
        }
      }

      if (firstTimestamp === undefined) {
        const ts = entry.timestamp
        if (typeof ts === 'string') {
          const ms = Date.parse(ts)
          if (Number.isFinite(ms) && ms > 0) firstTimestamp = ms
        }
      }

      const message = entry.message
      if (entry.type === 'system' && entry.subtype === 'api_error') {
        apiErrorCount += 1
      }
      if (!message || typeof message !== 'object') {
        if (bytesRead >= QUALITY_SCAN_MAX_BYTES && firstMessage !== undefined && cwd && sawAnyMessage) {
          qualityScanComplete = false
          break
        }
        continue
      }

      const msg = message as Record<string, unknown>
      const role = msg.role
      if (role !== 'user' && role !== 'assistant') {
        if (bytesRead >= QUALITY_SCAN_MAX_BYTES && firstMessage !== undefined && cwd && sawAnyMessage) {
          qualityScanComplete = false
          break
        }
        continue
      }
      sawAnyMessage = true

      if (role === 'user') {
        const isMeta = entry.isMeta
        if (isMeta !== true) {
          const text = extractTextFromContent(msg.content)
          if (text && !isFilteredMessage(text)) {
            userMessageCount += 1
            if (text.includes('[GA_TASK')) containsGaTask = true
            if (firstMessage === undefined) {
              firstMessage = truncate(text, 80)
            }
          }
        }
      }

      if (role === 'assistant') {
        const text = extractTextFromContent(msg.content)
        if (text) {
          assistantTextChars += text.length
          if (text.includes('[GA_TASK')) containsGaTask = true
        }
      }

      if (
        firstMessage !== undefined
        && cwd
        && sawAnyMessage
        && bytesRead >= QUALITY_SCAN_MAX_BYTES
      ) {
        qualityScanComplete = false
        break
      }
    }
  } finally {
    // Close the readline interface explicitly so Node releases the file handle
    // promptly even if we broke out of the loop early.
    rl.close()
    fileStream.destroy()
  }

  if (!sawAnyMessage) return null

  const fileName = filePath.replace(/[/\\]/g, '/').split('/').pop()!
  const sessionId = fileName.replace(/\.jsonl$/, '')
  if (!sessionId) return null

  return {
    sessionId,
    firstMessage: firstMessage ?? `Session ${sessionId.slice(0, 8)}`,
    firstTimestamp,
    lastTimestamp: lastTimestampMs,
    cwd,
    fileSizeBytes,
    userMessageCount,
    assistantTextChars,
    apiErrorCount,
    containsGaTask,
    qualityScanComplete
  }
}

/**
 * Find the Claude project directory for a given workspace path.
 * Handles path encoding, trailing slashes, and worktree prefix matching.
 */
export async function findClaudeProjectDir(
  baseDir: string,
  workspacePath: string
): Promise<string | null> {
  const encoded = encodeProjectPath(workspacePath)

  // Direct match
  const directDir = join(baseDir, encoded)
  try {
    const s = await stat(directDir)
    if (s.isDirectory()) return directDir
  } catch {
    // doesn't exist
  }

  // Try trimmed trailing slashes
  const trimmed = workspacePath.replace(/[/\\]+$/, '')
  if (trimmed !== workspacePath) {
    const encodedTrimmed = encodeProjectPath(trimmed)
    const trimmedDir = join(baseDir, encodedTrimmed)
    try {
      const s = await stat(trimmedDir)
      if (s.isDirectory()) return trimmedDir
    } catch {
      // doesn't exist
    }
  }

  // Fallback: scan all project dirs for prefix match
  // (handles worktree directories like E--path--worktrees-branch)
  try {
    const entries = await readdir(baseDir)
    for (const entry of entries) {
      if (entry.startsWith(encoded) && entry.length > encoded.length) {
        const nextChar = entry[encoded.length]
        if (nextChar === '-') {
          const matchDir = join(baseDir, entry)
          try {
            const s = await stat(matchDir)
            if (s.isDirectory()) return matchDir
          } catch {
            continue
          }
        }
      }
    }
  } catch {
    // base dir doesn't exist
  }

  return null
}

export type CliHistoryStore = ReturnType<typeof createCliHistoryStore>

async function readCliSessionCwd(filePath: string): Promise<string | undefined> {
  const fileStream = createReadStream(filePath, { encoding: 'utf-8', start: 0, end: QUALITY_SCAN_MAX_BYTES - 1 })
  const rl = createInterface({ input: fileStream, crlfDelay: Infinity })
  try {
    for await (const rawLine of rl) {
      const line = rawLine.trim()
      if (!line) continue
      try {
        const entry = JSON.parse(line) as Record<string, unknown>
        if (typeof entry.cwd === 'string' && entry.cwd.trim()) return entry.cwd.trim()
      } catch {
        continue
      }
    }
  } finally {
    rl.close()
    fileStream.destroy()
  }
  return undefined
}

/**
 * Match a Claude Code CLI session jsonl file to a Desk Session by mtime window.
 * Called on Desk Session exit when CC has finished writing its jsonl, so the
 * mtime is stable and the match window can be narrow.
 *
 * Strategy:
 *   1. Scan ~/.claude/projects/<encoded_path>/*.jsonl
 *   2. Filter to files whose mtime falls in [createdAtMs, exitedAtMs + slackMs]
 *   3. Pick the one with mtime closest to exitedAtMs (most likely the one we just produced)
 *
 * Returns the cliSessionId (jsonl filename without `.jsonl`) or null if no match.
 * `slackMs` accounts for fsync delay between CC's last write and our exit hook firing.
 */
export async function matchCliSessionByMtime(input: {
  workspacePath: string
  createdAtMs: number
  exitedAtMs: number
  slackMs?: number
  claudeProjectsBaseDir?: string
}): Promise<string | null> {
  const slack = input.slackMs ?? 5000
  const baseDir = input.claudeProjectsBaseDir ?? claudeProjectsDir()
  const projectDir = await findClaudeProjectDir(baseDir, input.workspacePath)
  if (!projectDir) return null

  let entries: string[]
  try {
    entries = await readdir(projectDir)
  } catch {
    return null
  }

  type Candidate = { sessionId: string; mtimeMs: number }
  const candidates: Candidate[] = []

  for (const entry of entries) {
    if (!entry.endsWith('.jsonl') || entry.startsWith('agent-')) continue
    const filePath = join(projectDir, entry)
    let mtimeMs: number
    try {
      mtimeMs = (await stat(filePath)).mtimeMs
    } catch {
      continue
    }
    if (mtimeMs < input.createdAtMs || mtimeMs > input.exitedAtMs + slack) continue
    const cwd = await readCliSessionCwd(filePath)
    if (!cwd || normalizePath(cwd) !== normalizePath(input.workspacePath)) continue
    const sessionId = entry.replace(/\.jsonl$/, '')
    if (!sessionId) continue
    candidates.push({ sessionId, mtimeMs })
  }

  if (candidates.length === 0) return null

  candidates.sort((a, b) => Math.abs(a.mtimeMs - input.exitedAtMs) - Math.abs(b.mtimeMs - input.exitedAtMs))
  return candidates[0].sessionId
}

export function createCliHistoryStore(deps: { getProjectPath: (projectId: string) => Promise<string>; claudeProjectsBaseDir?: string }) {
  /** Cache of sessionId -> projectPath for getCliSessionOutput lookups */
  const sessionProjectPathMap = new Map<string, string>()
  const claudeProjectsBaseDir = deps.claudeProjectsBaseDir ?? claudeProjectsDir()

  return {
    /**
     * List Claude Code CLI history sessions for a given project.
     * Scans ~/.claude/projects/{encoded_path}/*.jsonl files.
     */
    async listCliHistory(projectId: string): Promise<CliHistorySession[]> {
      const projectPath = await deps.getProjectPath(projectId)
      const baseDir = claudeProjectsBaseDir
      const projectDir = await findClaudeProjectDir(baseDir, projectPath)

      if (!projectDir) return []

      let entries: string[]
      try {
        entries = await readdir(projectDir)
      } catch {
        return []
      }

      const results: CliHistorySession[] = []
      const scanPromises: Promise<void>[] = []

      for (const entry of entries) {
        // Only .jsonl files, skip agent-* subagent sessions
        if (!entry.endsWith('.jsonl') || entry.startsWith('agent-')) continue

        const filePath = join(projectDir, entry)
        const promise = scanCliSessionFile(filePath).then((scanned) => {
          if (!scanned) return
          sessionProjectPathMap.set(scanned.sessionId, projectPath)
          const now = new Date().toISOString()
          results.push({
            id: scanned.sessionId,
            projectId,
            firstMessage: scanned.firstMessage,
            createdAt: scanned.firstTimestamp
              ? new Date(scanned.firstTimestamp).toISOString()
              : now,
            updatedAt: scanned.lastTimestamp
              ? new Date(scanned.lastTimestamp).toISOString()
              : now,
            fileSizeBytes: scanned.fileSizeBytes,
            cwd: scanned.cwd,
            userMessageCount: scanned.userMessageCount,
            assistantTextChars: scanned.assistantTextChars,
            apiErrorCount: scanned.apiErrorCount,
            containsGaTask: scanned.containsGaTask,
            qualityScanComplete: scanned.qualityScanComplete,
            source: 'cli'
          })
        })
        scanPromises.push(promise)
      }

      await Promise.all(scanPromises)

      results.sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))

      return results
    },

    /**
     * Read the full text output of a CLI history session.
     * Requires projectId to independently locate the session file
     * (no longer depends on the sessionProjectPathMap cache).
     * Uses readline + createReadStream to avoid OOM on large files.
     * Each user message is prefixed with ">>> " and each assistant message with "<<< ".
     */
    async getCliSessionOutput(sessionId: string, projectId: string): Promise<string> {
      const cachedProjectPath = sessionProjectPathMap.get(sessionId)
      const projectPath = projectId ? await deps.getProjectPath(projectId) : cachedProjectPath
      if (!projectPath) {
        throw new Error(`CLI session project not found: ${sessionId}`)
      }
      const baseDir = claudeProjectsBaseDir
      const projectDir = await findClaudeProjectDir(baseDir, projectPath)
      if (!projectDir) {
        throw new Error(`Claude project directory not found for project: ${projectId}`)
      }

      const filePath = join(projectDir, `${sessionId}.jsonl`)

      try {
        await stat(filePath)
      } catch {
        throw new Error(`CLI session file not found: ${sessionId}`)
      }

      const parts: string[] = []
      const fileStream = createReadStream(filePath, { encoding: 'utf-8' })
      const rl = createInterface({ input: fileStream, crlfDelay: Infinity })

      for await (const rawLine of rl) {
        const line = rawLine.trim()
        if (!line) continue

        let entry: Record<string, unknown>
        try {
          entry = JSON.parse(line) as Record<string, unknown>
        } catch {
          continue
        }

        const message = entry.message
        if (!message || typeof message !== 'object') continue

        const msg = message as Record<string, unknown>
        const role = msg.role
        if (role !== 'user' && role !== 'assistant') continue

        // Skip meta entries
        if (entry.isMeta === true) continue

        const text = extractTextFromContent(msg.content)
        if (text) {
          const prefix = role === 'user' ? '>>> ' : '<<< '
          parts.push(prefix + text)
        }
      }

      return parts.join('\n\n')
    },

    /**
     * Search CLI history sessions for a given project.
     * Searches firstMessage and message text; returns matching sessions with excerpts.
     */
    async searchCliHistory(projectId: string, query: string): Promise<SearchSessionResult[]> {
      const normalizedQuery = query.toLocaleLowerCase()
      if (normalizedQuery.length === 0) return []

      const projectPath = await deps.getProjectPath(projectId)
      const baseDir = claudeProjectsBaseDir
      const projectDir = await findClaudeProjectDir(baseDir, projectPath)
      if (!projectDir) return []

      let entries: string[]
      try {
        entries = await readdir(projectDir)
      } catch {
        return []
      }

      const results: SearchSessionResult[] = []

      for (const entry of entries) {
        if (!entry.endsWith('.jsonl') || entry.startsWith('agent-')) continue

        const filePath = join(projectDir, entry)
        const sessionId = entry.replace(/\.jsonl$/, '')

        let matched = false
        let title = `Session ${sessionId.slice(0, 8)}`
        let excerpt = ''

        const fileStream = createReadStream(filePath, { encoding: 'utf-8' })
        const rl = createInterface({ input: fileStream, crlfDelay: Infinity })
        let shouldStop = false

        for await (const rawLine of rl) {
          if (shouldStop) break
          const line = rawLine.trim()
          if (!line) continue

          let parsed: Record<string, unknown>
          try {
            parsed = JSON.parse(line) as Record<string, unknown>
          } catch {
            continue
          }

          const message = parsed.message
          if (!message || typeof message !== 'object') continue

          const msg = message as Record<string, unknown>
          const role = msg.role
          if (role !== 'user' && role !== 'assistant') continue
          if (parsed.isMeta === true) continue

          const text = extractTextFromContent(msg.content)
          if (!text) continue

          // Capture first user message as title
          if (role === 'user' && title.startsWith('Session ')) {
            title = truncate(text, 80)
          }

          // Search text for query
          if (!matched && text.toLocaleLowerCase().includes(normalizedQuery)) {
            matched = true
            const index = text.toLocaleLowerCase().indexOf(normalizedQuery)
            const start = Math.max(0, index - 60)
            excerpt = text.slice(start, start + 160)
          }

          if (matched && !title.startsWith('Session ')) {
            shouldStop = true
          }
        }

        if (matched) {
          results.push({
            sessionId,
            title,
            status: 'exited',
            matchedAt: new Date().toISOString(),
            excerpt
          })
        }
      }

      return results
    }
  }
}
